<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Empfänger zu Kontakten';
$labels['prefs_option']  = 'Benutze das Plugin "Empfänger zu Kontakten"';
$labels['prefs_descr'] = 'Das Plugin "Empfänger zu Kontakten" zeigt nach dem Senden von E-Mails an neue Empfänger ein Formular zum schnellen Hinzufügen dieser an.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Ihre Nachricht wurde an die folgenden Empfänger gesendet:';
$labels['dialog_contact_name'] = 'Kontaktname';
$labels['dialog_contact_firstname'] = 'Vorname';
$labels['dialog_contact_surname'] = 'Nachname';
$labels['dialog_contact_addressbook'] = 'Adressbuch:';
$labels['dialog_contact_group'] = 'Gruppe: ';
$labels['dialog_email'] = 'E-Mail-Adresse';
$labels['dialog_addressbook'] = 'Adressbuch';
$labels['dialog_add_selected'] = 'Auswahl hinzufügen zu: ';
$labels['dialog_adding'] = 'Hinzufügen...';

// various response messages
$labels['response_name_empty'] = 'Bitte geben Sie einen Kontaktnamen ein';
$labels['response_email_invalid'] = 'Bitte geben Sie eine gültige E-Mail-Adresse ein';
$labels['response_server_error'] = 'Server-Fehler';
$labels['response_addressbook_not_selected'] = 'Bitte wählen Sie ein Adressbuch';
$labels['response_contact_not_selected'] = 'Bitte wählen Sie mindestens einen Kontakt zum Hinzufügen';
$labels['response_confirm'] = 'Kontakt erfolgreich hinzugefügt';
?>