<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Recipients to contacts';
$labels['prefs_option']  = 'Use recipients to contacts plugin';
$labels['prefs_descr'] = 'Recipients to contacts plugin displays a form to quickly add new contacts, after the email has been sent to new recipients.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Your message was sent to the following recipients';
$labels['dialog_contact_name'] = 'Contact name';
$labels['dialog_contact_firstname'] = 'Firstname';
$labels['dialog_contact_surname'] = 'Surname';
$labels['dialog_contact_addressbook'] = 'Addressbook:';
$labels['dialog_contact_group'] = 'Group: ';
$labels['dialog_email'] = 'Email address';
$labels['dialog_addressbook'] = 'Address book';
$labels['dialog_add_selected'] = 'Add selected to: ';
$labels['dialog_adding'] = 'Adding...';

// various response messages
$labels['response_name_empty'] = 'Please enter a contact name';
$labels['response_email_invalid'] = 'Please enter a valid email address';
$labels['response_server_error'] = 'Server error';
$labels['response_addressbook_not_selected'] = 'Please select an adressbook';
$labels['response_contact_not_selected'] = 'Please select at least one contact to add';
$labels['response_confirm'] = 'Contacts added successfully';
?>