<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Contacts vers carnet';
$labels['prefs_option']  = 'Utiliser le plugin';
$labels['prefs_descr'] = 'Affiche un formulaire pour ajouter les nouveaux contacts au carnet d\'adresses.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Votre message a été envoyé aux contacts suivants:';
$labels['dialog_contact_name'] = 'Nom du contact';
$labels['dialog_contact_firstname'] = 'Prénom';
$labels['dialog_contact_surname'] = 'Nom';
$labels['dialog_contact_addressbook'] = 'Carnet d\'adresses:';
$labels['dialog_contact_group'] = 'Groupe: ';
$labels['dialog_email'] = 'Courriel';

// various response messages
$labels['response_name_empty'] = 'Veuillez entrer le nom du contact';
$labels['response_email_invalid'] = 'Veuillez entrer une adresse mail valide';
$labels['response_server_error'] = 'Erreur du serveur';
$labels['response_contact_not_selected'] = 'Veuillez sélectionner au moins un contact à ajouter';
$labels['response_confirm'] = 'Les contacts ont été créés avec succès';
