<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Automatikus címzettek';
$labels['prefs_option']  = 'A bővítmény használatának engedélyezése';
$labels['prefs_descr'] = 'Ha a címzett nem szerepel a címjegyzékben, egy űrlapot jelenít meg, ami lehetőséget nyújt a címzett rögzítésére.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Az üzenet az alábbi címzetteknek lett elküldve:';
$labels['dialog_contact_name'] = 'Címzett neve';
$labels['dialog_contact_firstname'] = 'Keresztnév';
$labels['dialog_contact_surname'] = 'Vezetéknév';
$labels['dialog_contact_addressbook'] = 'Címjegyzék:';
$labels['dialog_contact_group'] = 'Csoport: ';
$labels['dialog_email'] = 'Email cím';

// various response messages
$labels['response_name_empty'] = 'Adja meg a címzett nevét';
$labels['response_email_invalid'] = 'Adjon meg valódi email címet';
$labels['response_server_error'] = 'Szerver hiba';
$labels['response_contact_not_selected'] = 'Válasszon ki legalább egy címzetett a hozzáadáshoz';
$labels['response_confirm'] = 'A címzettek hozzáadása megtörtént'; 

