<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Recipient to Contact';
$labels['prefs_option']  = 'Usa il plugin';
$labels['prefs_descr'] = 'Recipient to Contact è un plugin che mostra un form per inserire una mail sconosciuta in rubrica, dopo avergli inviato una email.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'La mail è stata spedita alle seguenti caselle email';
$labels['dialog_contact_name'] = 'Nome visualizzato';
$labels['dialog_contact_firstname'] = 'Nome';
$labels['dialog_contact_surname'] = 'Cognome';
$labels['dialog_contact_addressbook'] = 'Rubrica:';
$labels['dialog_contact_group'] = 'Gruppo:';
// <--
$labels['dialog_email'] = 'Email';
$labels['dialog_addressbook'] = 'Rubrica';
$labels['dialog_add_selected'] = 'Aggiungi selezionati alla rubrica: ';
$labels['dialog_adding'] = 'Salvataggio...';

// various response messages
$labels['response_name_empty'] = 'Inserisci un \'nome visualizzato\'';
$labels['response_email_invalid'] = 'Inserisci un indirizzo email valido';
$labels['response_server_error'] = 'Errore del server';
$labels['response_addressbook_not_selected'] = 'Scegli una rubrica';
$labels['response_contact_not_selected'] = 'Seleziona almeno un contatto da aggiungere';
$labels['response_confirm'] = 'Contatti salvati con successo';
?>
