<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Destinatários para contatos';
$labels['prefs_option']  = 'Ativar destinatários para contatos';
$labels['prefs_descr'] = 'O plugin destinatários para contatos mostra uma caixa para que você possa adicionar os destinatários de mensagens ao seu catálogo de endereços após o envio de um e-mail.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Sua mensagem foi enviada aos seguintes destinatários:';
$labels['dialog_contact_name'] = 'Nome do contato';
$labels['dialog_contact_firstname'] = 'Primeiro nome';
$labels['dialog_contact_surname'] = 'Sobrenome';
$labels['dialog_contact_addressbook'] = 'Catálogo de endereços:';
$labels['dialog_contact_group'] = 'Grupo: ';
$labels['dialog_email'] = 'Endereço de e-mail';

// various response messages
$labels['response_name_empty'] = 'Por favor entre com um nome de contato';
$labels['response_email_invalid'] = 'Por favor entre com um e-mail válido';
$labels['response_server_error'] = 'Erro de servidor';
$labels['response_contact_not_selected'] = 'Por favor selecione ao menos um contato para adicionar';
$labels['response_confirm'] = 'Contato(s) adicionado(s) com sucesso';