<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Адрессат в список контактов';
$labels['prefs_option']  = 'Использовать плагин адрессат в список контактов';
$labels['prefs_descr'] = 'Плагин отображает форму для быстрого добавления новых котактов после отправки сообщения на email-адресса, отсутсвующим в адрессной книге.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Сообщение было отправлено следующим адрессатам:';
$labels['dialog_contact_name'] = 'Отображаемое имя';
$labels['dialog_email'] = 'Email адресс';
$labels['dialog_addressbook'] = 'Адрессная книга';
$labels['dialog_add_selected'] = 'Добавть выбранные в: ';

// various response messages
$labels['response_name_empty'] = 'Пожалуйста введите имя контакта';
$labels['response_email_invalid'] = 'Пожалуйста введите правильный email';
$labels['response_server_error'] = 'Ошибка сервера';
$labels['response_none_selected'] = 'Пожалуйста выберите список контактов';
$labels['response_confirm'] = 'Контакт успешно добавлен';
?>