<?php
$labels = array();

// labels used in settings view
$labels['prefs_title']  = 'Адресат в список контактов';
$labels['prefs_option']  = 'Использовать плагин адресат в список контактов';
$labels['prefs_descr'] = 'Плагин отображает форму для быстрого добавления новых котактов после отправки сообщения на email-адреса, отсутствующим в адрессной книге.';

// labels used in dialog in frontend
$labels['dialog_title'] = 'Сообщение было отправлено следующим адресатам:';
$labels['dialog_contact_name'] = 'Отображаемое имя';
$labels['dialog_contact_firstname'] = 'Firstname';
$labels['dialog_contact_surname'] = 'Surname';
$labels['dialog_contact_addressbook'] = 'Addressbook:';
$labels['dialog_contact_group'] = 'Group: ';
$labels['dialog_email'] = 'Email адресс';

// various response messages
$labels['response_name_empty'] = 'Пожалуйста введите имя контакта';
$labels['response_email_invalid'] = 'Пожалуйста введите правильный email';
$labels['response_server_error'] = 'Ошибка сервера';
$labels['response_contact_not_selected'] = 'Пожалуйста выберите по крайней мере один контакт';
$labels['response_confirm'] = 'Контакт успешно добавлен';